export enum ToolsyErrorMessageCodes {
  NOT_FOUND = 'NOT_FOUND',

  // Project
  PROJECT_BOT_TOKEN_INVALID_BAD_REQUEST = 'PROJECT_BOT_TOKEN_INVALID_BAD_REQUEST',
  PROJECT_BOT_BANNED_CONFLICT = 'PROJECT_BOT_BANNED_CONFLICT',
  PROJECT_BOT_ALREADY_EXISTS_CONFLICT = 'PROJECT_BOT_ALREADY_EXISTS_CONFLICT',

  // PromoCode
  PROMO_CODE_ALREADY_EXISTS_CONFLICT = 'PROMO_CODE_ALREADY_EXISTS_CONFLICT',
}
